/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'glass-border': 'rgba(255, 255, 255, 0.1)',
        'glass-surface': 'rgba(15, 23, 42, 0.65)',
        'primary-fixed-dim': '#adc6ff',
        'secondary-fixed-dim': '#89ceff',
        'secondary-container': '#00a2e6',
        'on-secondary-fixed': '#001e2f',
        'surface': '#0c1324',
        'surface-dim': '#0c1324',
        'tertiary-fixed-dim': '#d0bcff',
        primary: '#adc6ff',
        'primary-container': '#4d8eff',
        'primary-fixed': '#d8e2ff',
        'on-primary': '#002e6a',
        'on-primary-fixed': '#001a42',
        'on-primary-fixed-variant': '#004395',
        'inverse-primary': '#005ac2',
        'on-primary-container': '#00285d',
        'surface-tint': '#adc6ff',
        secondary: '#89ceff',
        'secondary-fixed': '#c9e6ff',
        'on-secondary-fixed-variant': '#004c6e',
        'on-secondary': '#00344d',
        'on-secondary-container': '#00344e',
        tertiary: '#d0bcff',
        'tertiary-container': '#a078ff',
        'tertiary-fixed': '#e9ddff',
        'on-tertiary-fixed': '#23005c',
        'on-tertiary-fixed-variant': '#5516be',
        'on-tertiary': '#3c0091',
        'on-tertiary-container': '#340080',
        'inverse-surface': '#dce1fb',
        'inverse-on-surface': '#2a3043',
        'on-surface': '#dce1fb',
        'on-surface-variant': '#c2c6d6',
        'surface-variant': '#2e3447',
        'outline-variant': '#424754',
        'surface-container': '#191f31',
        'surface-container-low': '#151b2d',
        'surface-container-lowest': '#070d1f',
        'surface-container-high': '#23293c',
        'surface-container-highest': '#2e3447',
        'surface-bright': '#33394c',
        background: '#0c1324',
        outline: '#8c909f',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'obsidian-deep': '#020617',
        'success-glow': '#10b981',
        'warning-glow': '#f59e0b',
        'danger-glow': '#ef4444',
      },
      borderRadius: {
        DEFAULT: '4px',
        lg: '8px',
        xl: '12px',
        '2xl': '16px',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '16px',
        'margin-desktop': '40px',
        'stack-lg': '32px',
        'stack-md': '16px',
        'stack-sm': '8px',
        unit: '4px',
        gutter: '24px',
        'container-max': '1280px',
      },
      fontFamily: {
        'display-lg': ['Inter'],
        'headline-lg': ['Inter'],
        'headline-md': ['Inter'],
        'body-md': ['Inter'],
        'body-lg': ['Inter'],
        'label-sm': ['JetBrains Mono'],
        'label-md': ['JetBrains Mono'],
        'font-mono': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '1.4', letterSpacing: '0.05em', fontWeight: '500' }],
        'label-md': ['14px', { lineHeight: '1.4', letterSpacing: '0.05em', fontWeight: '500' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.2', fontWeight: '600' }],
      },
      backdropBlur: {
        xl: '20px',
      },
      boxShadow: {
        'glass': '0 8px 32px rgba(0, 0, 0, 0.3)',
        'primary-glow': '0 0 15px rgba(173, 198, 255, 0.3)',
        'success-glow': '0 0 15px rgba(16, 185, 129, 0.3)',
        'danger-glow': '0 0 15px rgba(239, 68, 68, 0.3)',
        'qr-glow': '0 0 20px rgba(255, 255, 255, 0.1)',
      },
    },
  },
  plugins: [],
};